version: "3.9"

services:
  bet_maker:
    build:
      context: ./bet_maker
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    depends_on:
      - db

  rabbit_worker:
    build:
      context: ./bet_maker
      dockerfile: ./Dockerfile
    command: python rabbit_worker.py
    ports:
      - "8004:8003"
    depends_on:
      - rabbitmq

  line_provider:
    build:
      context: ./line_provider
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bets
    ports:
      - 5438:5432
    volumes:
      - db_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "mycookie"
      RABBITMQ_DEFAULT_USER: "bet_service"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq


volumes:
  db_data:
  rabbitmq_data:
  rabbitmq_logs:
