version: "3.9"

services:
  bet_maker:
    build:
      context: ./bet_maker
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    depends_on:
      - db

  line_provider:
    build:
      context: ./line_provider
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bets
    ports:
      - 5439:5432
    volumes:
      - db_data:/var/lib/postgresql/data/


volumes:
  db_data:
